
path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug : './out/debug'

reflector :

  reflect.proto :
    inherit : predefined.*
    filePath :
      path::proto : path::out.debug

step :

  reflect.proto :
    inherit : files.reflect
    filePath :
      reflector::reflect.proto

  delete.out.debug :
    inherit : files.delete
    filePath : path::out.debug

build :

  debug :
    criterion :
      default : 1
    steps :
      - delete.out.debug
      - reflect.proto
