
submodule :

  ModuleForTesting1 : git+https:///github.com/Wandalen/wModuleForTesting1.git/#4418bd34a5fc1a89c6bd992cc17651875ee89583
  ModuleForTesting2a : git+https:///github.com/Wandalen/wModuleForTesting2a.git/!master
  ModuleForTesting12ab : git+https:///github.com/Wandalen/wModuleForTesting12ab.git/#5825b2537e6dcc1c2ca14fe4cedb8d9917bf17c8

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      debug : 1
    filePath :
      path::proto : path::out.*=1

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      basePath : .
      prefixPath : path::out.debug
    criterion :
      debug : 1

step :

  delete.out.debug :
    inherit : files.delete
    filePath : path::out.debug
    criterion :
      debug : 1

build :

  debug.raw :
    criterion :
      default : 1
    steps :
      - submodules.download
      - delete.out.debug
      - reflect.proto*=1
      - reflect.submodules*=1
