
path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1
  out.release :
    path : './out/release'
    criterion :
      debug : 0

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      debug : 1
    filePath :
      path::proto : path::out.*=1

  reflect.submodules1 :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    criterion :
      debug : 1
    dst :
      basePath : .
      prefixPath : path::out.debug

  reflect.submodules2 :
    inherit : predefined.*
    criterion :
      debug : 1
    filePath :
      submodule::*/exported::*=1/path::exported.dir*=1 : path::out.*=1

step :

  reflect.proto :
    inherit : files.reflect
    filePath :
      reflector::reflect.proto

  reflect.submodules1 :
    inherit : files.reflect
    filePath :
      reflector::reflect.submodules1

  reflect.submodules2 :
    inherit : files.reflect
    filePath : reflector::reflect.submodules2

build :

  debug.raw :
    criterion :
      default : 1
    steps :
      - step::reflect.proto
