
about :

  name : submodule2
  version : 0.0.0

submodule :
  submodule1 : ../module1/

path :
  out : out

step :

  export :
    export : 'proto/**'

build :

  export :
    steps : export
    criterion :
      export : 1
      default : 1
