
about :

    name : buildModuleWithCriterion
    description : "Output of various phrases using criterions"
    version : 0.0.1

step :

  print.one :
    shell : echo "Debug is done"
    currentPath : '.'
    criterion :
       debug : 1

  print.two :
    shell : echo "Operation is done"
    currentPath : '.'
    criterion :
       debug : 0

build :

  print.debug :
    criterion :
       debug : 1
    steps :
       - print.*

  print.test :
    criterion :
       debug : 1
    steps :
       - print.one
       - print.two

