
about :

  name : "module-aab"
  description : "Module for testing"
  version : "0.0.1"

submodule :

  sub-a : ../out/module-a.out
  sub-ab : ../out/ab/module-ab.out

path :

  proto : '../proto'
  out : '../out/aab'
  files : '{path::out}/files'
  temp :
    - ../out
    - ../out2
  export :
    - 'module::sub-a/path::exported.files.proto.export'
    - 'module::sub-b/path::exported.files.proto.export'
    - '{path::proto}/dir3.test'

reflector :

  files.all :
    src :
      recursive : 1
      filePath :
        'module::sub-a/reflector::exported.files.proto.export' : '{path::files}/a'
        'module::sub-b/reflector::exported.files.proto.export' : '{path::files}/b'
        '{path::proto}/dir3.test' : '{path::files}/dir3.test'

step :

  export.proto :
    export : 'path::export'
    tar : 0

build :

  files :
    criterion :
      default : 1
    steps :
      - step::files.all

  proto.export :
    criterion :
      default : 1
      export : 1
    steps :
      - step::export.proto
