
path :

  google : http:///www.google.com
  localPath : File.html

step :

  view1 :
    inherit : file.view
    filePath : path::google
    delay : 3000

  view2 :
    inherit : file.view
    filePath : path::localPath

build :

  view1 :
    steps :
      - step::view1

  view2 :
    steps :
      - step::view2
