
path :

  google : http:///www.google.com
  localPath : File.html

step :

  view.remote :
    inherit : file.view
    filePath : path::google
    delay : 3000

  view.local :
    inherit : file.view
    filePath : path::localPath

build :

  view1 :
    steps :
      - step::view.remote

  view2 :
    steps :
      - step::view.local
