submodule :
  exportWhole : module/exportWhole.out

about :

  name : "import-whole"
  description : "Module for testing"
  version : "0.0.1"
  enabled : 1

path :

  in : '.'
  out : 'out'
  temp : '*out*'

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst : path::out

build :
  debug :
    criterion :
      default : 1
    steps :
    - step::reflect.submodules
