
about :

  name : "submodulesDetached"
  version : "0.0.1"

step :

  export.proto :
    inherit : module.export
    export : '{path::proto}/**'
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      export : 1
    steps :
      - build::debug
      - step::export.proto
