
submodule :

  submodule : submodule.out

path :

  in : '.'
  out : './out'
  out.debug :
    path : './out/debug/**'
  temp :
    - path::out
    - submodule.out.will.yml

reflector :

  reflect.submodules.variant :
    inherit : predefined.*
    filePath :
      submodule::*/exported::*=1/path::exported.dir*=1 : path::out.*=1
    src :
      basePath : "{submodule::*/exported::*=1/path::exported.dir*=1}/.."
    criterion :
      variant : 1

  reflect.submodules.variant2 :
    inherit : predefined.*
    filePath :
      . : path::out.*=1
    src :
      basePath : ..
      prefixPath : "{submodule::*/exported::*=1/path::exported.dir*=1}"
    criterion :
      variant : 2

  reflect.submodules.variant3 :
    inherit : predefined.*
    filePath :
      submodule::*/exported::*=1/path::exported.dir*=1 : path::out.*=1
    src :
      basePath : 'module'
    criterion :
      variant : 3

step :

  reflect.submodules :
    inherit : files.reflect
    criterion :
      variant : [ 1,2,3 ]
    filePath :
      reflector::reflect.submodules.*=1

build :

  debug :
    criterion :
      default : 1
      variant : [ 1,2,3 ]
    steps :
      - step::reflect.submodules.*=1
