
submodule :

  # ModuleForTesting2 : git+https:///github.com/Wandalen/wModuleForTesting2.git/out/wModuleForTesting2.out.will!master
  ModuleForTesting12 : git+hd://../_repo/ModuleForTesting12/

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug : './out/debug'

reflector :

  reflect.submodules1 :
    inherit : predefined.*
    filePath :
      submodule::*/path::proto*=1 : path::out.*=1

  reflect.submodules2 :
    inherit : predefined.*
    src :
      filePath :
        submodule::*/path::proto*=1 : path::out.*=1

  reflect.submodules3 :
    inherit : predefined.*
    src :
      basePath : submodule::*/path::proto*=1
      filePath :
        submodule::*/path::proto*=1 : path::out.*=1

step :

  reflect.submodules1 :
    inherit : files.reflect
    filePath :
      reflector::reflect.submodules1

  reflect.submodules2 :
    inherit : files.reflect
    filePath :
      reflector::reflect.submodules2

  reflect.submodules3 :
    inherit : files.reflect
    filePath :
      reflector::reflect.submodules3

build :

  debug1 :
    steps :
      - submodules.download
      - reflect.submodules1

  debug2 :
    steps :
      - submodules.download
      - reflect.submodules2

  debug3 :
    steps :
      - submodules.download
      - reflect.submodules3
