
step :

  verbosity.0 :
    currentPath : .
    shell : node -e "console.log( 'message from shell' )"
    verbosity : 0

  verbosity.1 :
    currentPath : .
    shell : node -e "console.log( 'message from shell' )"
    verbosity : 1

  verbosity.2 :
    currentPath : .
    shell : node -e "console.log( 'message from shell' )"
    verbosity : 2

  verbosity.3 :
    currentPath : .
    shell : node -e "console.log( 'message from shell' )"
    verbosity : 3

  verbosity.5 :
    currentPath : .
    shell : node -e "console.log( 'message from shell' )"
    verbosity : 5

build :

  verbosity.0 :
    steps :
      - verbosity.0

  verbosity.1 :
    steps :
      - verbosity.1

  verbosity.2 :
    steps :
      - verbosity.2

  verbosity.3 :
    steps :
      - verbosity.3

  verbosity.5 :
    steps :
      - verbosity.5
