about :
  name : reflectorOptionsCheck
  description : "To check applying default options in reflector"
  version : 0.0.1

path :

  in : '.'
  out : 'out'
  export : '{path::proto}/**'
  proto : 'proto'
  file1 : 'proto/File.js'
  file2 : 'proto/File2.js'

reflector :

  reflect.withoutOptions :
    filePath :
      path::file1 : '{path::out}/debug/File.js'

  reflect.defaultOptions :
    filePath :
      path::file2 : '{path::out}/debug/File.js'
    linking : hardLinkMaybe
    dstRewritingOnlyPreserving : 1
    mandatory : 1

  reflect.notDefaultOptions :
    inherit : predefined.*
    filePath :
      path::file2 : '{path::out}/debug/File.js'
    linking : fileCopy
    dstRewritingOnlyPreserving : 0
    mandatory : 0

build :

  export :
    criterion :
      default : 1
      export : 1
    steps :
      - step::module.export
