
about :

  options1 : op1
  options2 :
    - op2
    - op3
  options3 :
    a :
      - op1
      - op2
    b :
      - op3
      - op4

path :

  proto : proto
  produce : '{path::proto}/Produce.js'
  path1 : '{path::proto}/File1.js'
  paths :
    - '{path::proto}/File2.js'
    - '{path::proto}/File3.js'
  temp :
    - out1.js
    - out2.js

step :

  strings.join :
    shell : 'node proto/Produce.js {path::paths/f::strings.join} {path::path1} out1.js'

  multiply :
    shell : 'node proto/Produce.js {path::paths} {path::path1} out2.js'

  echo1 :
    shell : 'node proto/Echo.js {path::paths/f::strings.join} {about::options2}'

  echo2 :
    shell : 'node proto/Echo.js {about::options2/f::strings.join} {about::options3/a}'

build :

  strings.join :
    steps :
      - strings.join

  multiply :
    steps :
      - multiply

  echo1 :
    steps :
      - echo1

  echo2 :
    steps :
      - echo2
