
about :

  name : "transpile"
  description : "Module for testing"
  version : "0.0.1"

step :

  export :
    inherit : predefined.export
    export : path::out.*=1
    tar : 1
    criterion :
      debug : [ 0,1 ]

build :

  export :
    criterion :
      default : 1
      debug : [ 0,1 ]
      raw : [ 0,1 ]
      export : 1
    steps :
      - build::*=1.raw
      - step::export*=1
