about :
  name : reflectorsCommonPrefix
  version : 0.0.1

path :

  in : '.'
  out : 'out'
  proto : './proto'
  out.debug : './out/debug'
  src : proto
  temp :
    - out

reflector :

  reflect.copy :
    src : 'path::src'
    dst : 'path::out.debug'

  reflect.copy.second :
    src : 'path::src'
    dst : 'path::out.debug'

build :

  copy :
    criterion :
      default : 1
    steps :
      - reflect.copy
      - reflect.copy.second
