
about :

  name : 'NpmFromWillfile'
  description : 'To check the conversion'
  version : '0.0.0'
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - tools
  - export
  license : MIT
  author : 'Author <author@dot.com>'
  contributors :
  - 'Contributor1 <contributor1@dot.com>'
  - 'Contributor2 <contributor2@dot.com>'
  npm.name : 'npmfromwillfile'
  npm.scripts :
    test : wtest .run proto/** v:5
    docgen : wdocgen .build proto

path :

  repository : git+https:///github.com/author/NpmFromWillfile.git
  origins :
   - git+https:///github.com/author/NpmFromWillfile.git
   - npm:///npmfromwillfile
  bugtracker : https:///github.com/author/NpmFromWillfile/issues

step :

  export.debug :
    inherit : module.export
    export : '{path::out}/**'
    criterion :
      debug : 1

build :

  proto.export :
    criterion :
      export : 1
      debug : 1
    steps :
      - step::export.*=1

