
about :

  name : supermodule
  version : 0.1.0

submodule :

  submodule : git+hd://module/?out=out/submodule.out.will!master

path :

  in : .
  out : out

build :

  debug :
    criterion :
      default : 1
      debug : 1
    steps :
      - step::submodules.download

