
submodule :

  wTools :
    path : npm:///wTools
    enabled : 0 # submodule
  wStringer :
    path : npm:///wstringer
    enabled : 0 # submodule
  wStringsExtra :
    path : npm:///wstringsextra
    enabled : 0 # submodule
  wConsequence :
    path : npm:///wConsequence
    enabled : 0 # submodule
  wCopyable :
    path : npm:///wCopyable
    enabled : 0 # submodule
  wGdfStrategy :
    path : npm:///wgdfstrategy
    enabled : 0 # submodule
  wRoutineBasic :
    path : npm:///wroutinebasic
    enabled : 0 # submodule
  wPathBasic :
    path : npm:///wpathbasic
    enabled : 0 # submodule
  wPathTools :
    path : npm:///wpathtools
    enabled : 0 # submodule
  wUriBasic :
    path : npm:///wuribasic
    enabled : 0 # submodule
  wWebUriBasic :
    path : npm:///wweburibasic
    enabled : 0 # submodule
  wAppBasic :
    path : npm:///wappbasic
    enabled : 0 # submodule
  wFieldsStack :
    path : npm:///wfieldsstack
    enabled : 0 # submodule
  wRegexpObject :
    path : npm:///wRegexpObject
    enabled : 0 # submodule
  wSelector :
    path : npm:///wselector
    enabled : 0 # submodule
  wVerbal :
    path : npm:///wverbal
    enabled : 0 # submodule
  wLogger :
    path : npm:///wLogger
    enabled : 0 # submodule
  ini :
    path : npm:///ini
    enabled : 0 # submodule
  tar :
    path : npm:///tar
    enabled : 0 # submodule
  gitconfiglocal :
    path : npm:///gitconfiglocal
    enabled : 0 # submodule
  proper-lockfile :
    path : npm:///proper-lockfile
    enabled : 0 # submodule
  wFiles :
    path : hd://.
    enabled : 0 # submodule
    criterion :
      development : 1
  wait-sync :
    path : npm:///wait-sync
    enabled : 0 # submodule
    criterion :
      development : 1
  cli-table2 :
    path : npm:///cli-table2#^0.2.0
    enabled : 0 # submodule
    criterion :
      development : 1
  wTesting :
    path : npm:///wTesting
    enabled : 0 # submodule
    criterion :
      development : 1

path :

  in : '.'
  out : 'out'
  temp : 'path::out'
  proto : './proto'
  export : '{path::export}/**'
  doc : './doc'

  out.raw.debug :
    path : '{path::out}/debug'
    criterion :
      debug : debug
      raw : raw
      content : prime
  out.compiled.debug :
    path : '{path::out}/compiled.debug'
    criterion :
      debug : debug
      raw : compiled
      content : prime
  out.raw.release :
    path : '{path::out}/raw.release'
    criterion :
      debug : release
      raw : raw
      content : prime
  out.compiled.release :
    path : '{path::out}/release'
    criterion :
      debug : release
      raw : compiled
      content : prime

  entry.proto.no.tests :
    path : proto/dwtools/abase/l5/PathTools.s
    criterion :
      tests : 'no.tests'
  entry.proto.only.tests :
    path : proto/**/*.test.s
    criterion :
      tests : 'only.tests'

  # npm.entry : proto/dwtools/abase/Layer2.s
  # npm.files : proto

  entry.out.raw.debug :
    path : '{path::out.*=1}/source/dwtools/abase/l5/PathTools.s'
    criterion :
      debug : [ debug, release ]
      raw : raw
      content : prime
  entry.out.compiled.debug :
    path : '{path::out.*=}/source/Index.s'
    criterion :
      debug : [ debug, release ]
      raw : compiled
      content : prime

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      tests : 'no.tests'
      debug : [ debug, release ]
      raw : [ raw, compiled ]
      content : prime
    filePath :
      path::proto : '{path::out.*=1}/source'

  transpile.proto.raw :
    inherit : predefined.*
    step :
      inherit : files.transpile
      entry : path::entry.proto.no.tests
    criterion :
      raw : raw
      debug : release
      content : prime
    filePath :
      path::proto : '{path::out.raw.release}'

  transpile.proto.no.tests.compiled :
    inherit : predefined.*
    step :
      inherit : files.transpile
      entry : path::entry.proto.*=1
    criterion :
      tests : 'no.tests'
      raw : compiled
      debug : [ debug, release ]
      content : prime
    filePath :
      '**.test*' : 0
      '**.test/**' : 0
      path::proto : '{path::out.*=1}/Main.s'

  transpile.proto.only.tests.compiled :
    inherit : predefined.*
    step :
      inherit : files.transpile
      entry : path::entry.proto.*=1
      external.before : '{path::out.*=1}/Main.s'
    criterion :
      tests : 'only.tests'
      raw : compiled
      debug : [ debug, release ]
      content : prime
    filePath :
      '**.test*' : 1
      path::proto : '{path::out.*=1}/Tests.test.s'

step :

  npm.generate :
    inherit : npm.generate
    entryPath : path::entry.out.*=1
    packagePath : '{path::out.*=1}/package.json'
    filesPath : '{path::out.*=1}/source/**'
    criterion :
      debug : [ debug, release ]
      raw : [ raw, compiled ]

  clean.out :
    inherit : files.delete
    filePath : '{path::out.*=1}/source'
    criterion :
      debug : [ debug, release ]
      raw : [ raw, compiled ]
      tests : [ 'no.tests', 'only.tests' ]
      content : [ 'prime', 'npm' ]

  clean.out.npm :
    inherit : files.delete
    filePath : path::out.*=1
    criterion :
      debug : debug
      raw : compiled
      tests : no.tests
      content : npm

  tst.proto :
    shell : 'tst {path::proto}'
    criterion :
      content : proto

  tst.debug :
    shell : 'tst {path::out.*=1}'
    criterion :
      content : prime
      debug : debug

  tst.release :
    shell : 'tst {path::out.*=1}'
    criterion :
      content : prime
      debug : release

build :

  debug :
    criterion :
      default : 1
      debug : debug
      raw : raw
      content : prime
    steps :
      - step::clean.out*=2
      - reflect.proto.*=1

  compiled.debug :
    criterion :
      debug : debug
      raw : compiled
      content : prime
    steps :
      - step::clean.out*=2
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1

  raw.release :
    criterion :
      debug : release
      raw : raw
      content : prime
    steps :
      - step::clean.out*=2
      - transpile.proto.raw

  release :
    criterion :
      debug : release
      raw : compiled
      content : prime
    steps :
      - step::clean.out*=2
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1

  npm :
    criterion :
      debug : debug
      raw : raw
      content : npm
    steps :
      - npm.generate.*=1
      # - npm.generate

  all :
    steps :
      - build::debug
      - build::compiled.debug
      - build::raw.release
      - build::release
      - build::npm
