submodule :
  submodule2 : ./module2/
  submodule1 : ./module1/

about :

  name : supermodule
  version : 0.1.0

path :

  in : .
  out : out

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    criterion :
      debug : 1
    dst :
      basePath : .
      prefixPath : "{path::out}"

build :

  debug :
    criterion :
      default : 1
      debug : 1
    steps :
      - submodules.reload
      - reflect.submodules
