
path :

  ModuleForTesting1.remote : https:///raw.githubusercontent.com/Wandalen/wModuleForTesting1/master/proto/dwtools/testing/l1/ModuleForTesting1.s
  ModuleForTesting1.local : 'ModuleForTesting1.s'

reflector :

  download.1 :
    criterion :
      variant : 1
    filePath :
      path::ModuleForTesting1.remote : out/ModuleForTesting1.s

build :

  download :
    criterion :
      variant : [ 1 ]
    steps :
      - step::download.*=1
