
about :

  name : many
  version : 0.1.0

step :

  export.out :
    inherit : module.export
    export : '{path::out.proto}/**'
    tar : 0
    criterion :
      debug : 1
      content: proto

build :

  proto.export :
    criterion :
      default : 1
      export : 1
      content: proto
    steps :
      - build::build
      - step::export.out
