
submodule :

  submodule : submodule.out

path :

  in : '.'
  out : './out/*'
  out.debug : './out/debug/*'
  temp :
    - out
    - submodule.out.will.yml

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      basePath : .
      prefixPath : "{path::out.*=1}"
    criterion :
      debug : [ 0,1 ]

step :

  submodules.informal.export :
    shell : 'node {path::will} .each module .export'

build :

  variant1 :
    criterion :
      default : 1
      debug : 1
    steps :
      - step::reflect.submodules.*=1

  variant2 :
    criterion :
      debug : 1
    steps :
      - step::submodules.informal.export
      - step::submodules.reload
      - step::reflect.submodules.*=1
