about :
  name : exportModule
  description : "To export single file"
  version : 0.0.1

path :
  in : '.'
  out : 'out'
  fileToExport : 'fileToExport*'

step  :
  export.single :
    inherit : module.export
    export : path::fileToExport
    tar : 0

build :
  export.single :
    criterion :
      default : 1
      export : 1
    steps :
      - export.single
