
path :

  in : '.'
  out : 'out'
  A : 'proto/A'
  B : 'proto/B'
  temp :
    - path::A
    - path::B

reflector :

  restore :
    src : '+proto'
    dst : 'proto'

step :

  files.delete.vd :
    inherit : files.delete
    filePath :
      - path::A
      - path::B

  files.delete.v0 :
    inherit : files.delete
    verbosity : 0
    filePath :
      - path::A
      - path::B

  files.delete.v1 :
    inherit : files.delete
    verbosity : 1
    filePath :
      - path::A
      - path::B

  files.delete.v3 :
    inherit : files.delete
    verbosity : 3
    filePath :
      - path::A
      - path::B

build :

  files.delete.vd :
    steps :
      - restore
      - files.delete.vd

  files.delete.v0 :
    steps :
      - restore
      - files.delete.v0

  files.delete.v1 :
    steps :
      - restore
      - files.delete.v1

  files.delete.v3 :
    steps :
      - restore
      - files.delete.v3
