about :

    name : predefinedSteps
    description : "To use predefined submodule control steps"
    version : 0.0.1

submodule :

    ModuleForTesting1 : git+hd://../_repo/ModuleForTesting1?out=out/wModuleForTesting1.out.will!delta
    ModuleForTesting12ab : git+hd://../_repo/ModuleForTesting12ab?out=out/wModuleForTesting12ab.out.will!delta
    # ModuleForTesting1 : git+https:///github.com/Wandalen/wModuleForTesting1.git/out/wModuleForTesting1.out.will!master
    # ModuleForTesting2 : git+https:///github.com/Wandalen/wModuleForTesting2.git/out/wModuleForTesting2.out.will!master

step :

    echo :
        shell: echo "Done"

build :

    download :
        steps :
           - submodules.download

    upgrade :
        steps :
           - submodules.update

    clean :
        steps :
           - submodules.clean

    build :
        criterion :
          default : 1
        steps :
           - submodules.clean
           - submodules.download
           - echo
