
about :

  name : 'Download'
  version : '0.0.0'

submodule :

  ModuleForTesting1 : git+https:///github.com/Wandalen/wModuleForTesting1.git/out/wModuleForTesting1.out.will!master

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
  temp : '{path::out}'

reflector :

  reflect.proto :
    inherit : predefined.*
    filePath :
      path::proto : path::out.*=1

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      basePath : .
      prefixPath : path::out.debug

step :

  delete.out.debug :
    inherit : files.delete
    filePath : path::out.debug
    criterion :
      debug : 1

  export.proto :
    inherit : module.export
    export : '{path::proto}/**'
    tar : 0

build :

  debug.raw :
    criterion :
      default : 1
    steps :
      - step::delete.out.debug
      - step::submodules.download
      - step::reflect.proto
      - step::reflect.submodules

  export :
    criterion :
      default : 1
      export : 1
    steps :
      - build::debug.raw
      - step::export.proto
